app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

# from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame


@main_bp.route("/")
def home_page():
    return render_template("home_page.html")


def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = detect_mask_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())

# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class>
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home_page.html
{% extends "template.html" %}
{% block content %}

<p>&nbsp;</p>
  <h1 class="entry-title" style="text-align: center;">Face Mask Detector</h1>
  <h1 class="entry-title" style="text-align: center;"><img style="font-size: 14px; font-family: -webkit-standard;" src="http://www.paolodavid.com/wp-content/img/mask.png" alt="" width="56" height="56" />&nbsp;&nbsp;<img src="http://www.paolodavid.com/wp-content/img/mask-2.png" alt="" width="56" height="56" /></h1>
  <p style="text-align: center;">COVID-19 face mask detector with OpenCV, Keras/TensorFlow, and Deep Learning</p>
  <p style="text-align: center;">Web-app created by Paolo David</p>
  <p style="text-align: center;"><img src="http://www.paolodavid.com/wp-content/img/github-2.png" alt="" width="26" height="26" />&nbsp;<a href="https://github.com/paolodavid">https://github.com/paolodavid</a></p>

<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img id="ciao" src="/static/images/stay-safe.jpg"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
$(document).ready(function(){
    $('#image-detector').attr('class', 'nav-item');
    $('#live').attr('class', 'nav-item active');
})

    function stop(){
        $("#ciao").attr("src", "/static/images/stay-safe.jpg");
        $("#stop").attr("class","btn btn-danger active");
        $("#start").attr("class","btn btn-outline-success");
    }
    function start(){
        $("#ciao").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class","btn btn-success active");
        $("#stop").attr("class","btn btn-outline-danger");
    }

</script>

{% endblock %}

app/templates/template.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>Face Mask Detector by Paolo David</title>
    <style>
        .footer-link{ color: inherit; }
        .footer-link:hover{ color: inherit; }
        body {
    margin: 0;
}

.wrapper {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}

.footer {
    margin-top: auto;
}
    </style>
</head>
<body>
<div class="wrapper">
    <div class="header">

    </div>
    <div class="content">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}

        <!--add custom content with inheritance-->
        {% block content %}
        {% endblock %}
    </div>

</div>
<!-- jQuery, Popper.js, and Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>